# Generated by Django 6.0.5 on 2026-06-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seller_request_status',
            field=models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('SELLER', 'Seller'), ('ADMIN', 'Admin')], default='USER', max_length=10),
        ),
    ]
